/*
 * Copyright (c) 2020 D4L data4life gGmbH / All rights reserved.
 *
 * D4L owns all legal rights, title and interest in and to the Software Development Kit ("SDK"),
 * including any intellectual property rights that subsist in the SDK.
 *
 * The SDK and its documentation may be accessed and used for viewing/review purposes only.
 * Any usage of the SDK for other purposes, including usage for the development of
 * applications/third-party applications shall require the conclusion of a license agreement
 * between you and D4L.
 *
 * If you are interested in licensing the SDK for your own applications/third-party
 * applications and/or if you’d like to contribute to the development of the SDK, please
 * contact D4L by email to help@data4life.care.
 */

package care.data4life.fhir.r4.model;

import com.squareup.moshi.Json;


/**
 * A code that indicates how the page is generated.
 *
 * @see <a href="http://hl7.org/fhir/guide-page-generation">GuidePageGeneration</a>
 */
public enum CodeSystemGuidePageGeneration {

    /**
     * Page is proper xhtml with no templating.  Will be brought across unchanged for standard post-processing.
     */
    @Json(name = "html")
    HTML,

    /**
     * Page is markdown with templating.  Will use the template to create a file that imports the markdown file prior to post-processing.
     */
    @Json(name = "markdown")
    MARKDOWN,

    /**
     * Page is xml with templating.  Will use the template to create a file that imports the source file and run the nominated XSLT transform (see parameters) if present prior to post-processing.
     */
    @Json(name = "xml")
    XML,

    /**
     * Page will be generated by the publication process - no source to bring across.
     */
    @Json(name = "generated")
    GENERATED,
}
