// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= BackboneElement

Generated from FHIR 3.0.1.11917 on 2019-06-14

== BackboneElement

Base definition for all elements that are defined inside a resource - but not those in a data type..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/BackboneElement[BackboneElement, window="_blank"]


=== Diagram

[plantuml, BackboneElement, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class BackboneElement {
	modifierExtension : Extension 0..*
}

--

=== Properties
modifierExtension:: May be used to represent additional information that is not part of the basic definition of the element, and that modifies the understanding of the element that contains it. Usually modifier elements provide negation or qualification. In order to make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.


