// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= DocumentReference

Generated from FHIR 3.0.1.11917 on 2019-06-14

== DocumentReference

A reference to a document.

FHIR Reference: http://hl7.org/fhir/StructureDefinition/DocumentReference[DocumentReference, window="_blank"]


=== Diagram

[plantuml, DocumentReference, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class DocumentReference {
	authenticator : Reference 0..1
	author : Reference 0..*
	class : CodeableConcept 0..1
	content : DocumentReferenceContent 1..*
	context : DocumentReferenceContext 0..1
	created : DateTime 0..1
	custodian : Reference 0..1
	description : String 0..1
	docStatus : CompositionStatus 0..1
	identifier : Identifier 0..*
	indexed : Instant 1..1
	masterIdentifier : Identifier 0..1
	relatesTo : DocumentReferenceRelatesTo 0..*
	securityLabel : CodeableConcept 0..*
	status : DocumentReferenceStatus 1..1
	subject : Reference 0..1
	type : CodeableConcept 1..1
}

--

=== Properties
authenticator:: Which person or organization authenticates that this document is valid.
author:: Identifies who is responsible for adding the information to the document.
class:: A categorization for the type of document referenced - helps for indexing and searching. This may be implied by or derived from the code specified in the DocumentReference.type.
content:: The document and format referenced. There may be multiple content element repetitions, each with a different format.
context:: The clinical context in which the document was prepared.
created:: When the document was created.
custodian:: Identifies the organization or group who is responsible for ongoing maintenance of and access to the document.
description:: Human-readable description of the source document. This is sometimes known as the "title".
docStatus:: The status of the underlying document.
identifier:: Other identifiers associated with the document, including version independent identifiers.
indexed:: When the document reference was created.
masterIdentifier:: Document identifier as assigned by the source of the document. This identifier is specific to this version of the document. This unique identifier may be used elsewhere to identify this version of the document.
relatesTo:: Relationships that this document has with other document references that already exist.
securityLabel:: A set of Security-Tag codes specifying the level of privacy/security of the Document. Note that DocumentReference.meta.security contains the security labels of the "reference" to the document, while DocumentReference.securityLabel contains a snapshot of the security labels on the document the reference refers to.
status:: The status of this document reference.
subject:: Who or what the document is about. The document can be about a person, (patient or healthcare practitioner), a device (e.g. a machine) or even a group of subjects (such as a document about a herd of farm animals, or a set of patients that share a common exposure).
type:: Specifies the particular kind of document referenced  (e.g. History and Physical, Discharge Summary, Progress Note). This usually equates to the purpose of making the document referenced.




== DocumentReferenceContent

The document and format referenced. There may be multiple content element repetitions, each with a different format..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/DocumentReference[DocumentReference, window="_blank"]


=== Diagram

[plantuml, DocumentReferenceContent, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class DocumentReferenceContent {
	attachment : Attachment 1..1
	format : Coding 0..1
}

--

=== Properties
attachment:: The document or URL of the document along with critical metadata to prove content has integrity.
format:: An identifier of the document encoding, structure, and template that the document conforms to beyond the base format indicated in the mimeType.




== DocumentReferenceContext

The clinical context in which the document was prepared..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/DocumentReference[DocumentReference, window="_blank"]


=== Diagram

[plantuml, DocumentReferenceContext, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class DocumentReferenceContext {
	encounter : Reference 0..1
	event : CodeableConcept 0..*
	facilityType : CodeableConcept 0..1
	period : Period 0..1
	practiceSetting : CodeableConcept 0..1
	related : DocumentReferenceContextRelated 0..*
	sourcePatientInfo : Reference 0..1
}

--

=== Properties
encounter:: Describes the clinical encounter or type of care that the document content is associated with.
event:: This list of codes represents the main clinical acts, such as a colonoscopy or an appendectomy, being documented. In some cases, the event is inherent in the typeCode, such as a "History and Physical Report" in which the procedure being documented is necessarily a "History and Physical" act.
facilityType:: The kind of facility where the patient was seen.
period:: The time period over which the service that is described by the document was provided.
practiceSetting:: This property may convey specifics about the practice setting where the content was created, often reflecting the clinical specialty.
related:: Related identifiers or resources associated with the DocumentReference.
sourcePatientInfo:: The Patient Information as known when the document was published. May be a reference to a version specific, or contained.




== DocumentReferenceContextRelated

Related identifiers or resources associated with the DocumentReference..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/DocumentReference[DocumentReference, window="_blank"]


=== Diagram

[plantuml, DocumentReferenceContextRelated, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class DocumentReferenceContextRelated {
	identifier : Identifier 0..1
	ref : Reference 0..1
}

--

=== Properties
identifier:: Related identifier to this DocumentReference. If both id and ref are present they shall refer to the same thing.
ref:: Related Resource to this DocumentReference. If both id and ref are present they shall refer to the same thing.




== DocumentReferenceRelatesTo

Relationships that this document has with other document references that already exist..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/DocumentReference[DocumentReference, window="_blank"]


=== Diagram

[plantuml, DocumentReferenceRelatesTo, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class DocumentReferenceRelatesTo {
	code : DocumentRelationshipType 1..1
	target : Reference 1..1
}

--

=== Properties
code:: The type of relationship that this document has with anther document.
target:: The target document of this relationship.


