// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= Meta

Generated from FHIR 3.0.1.11917 on 2019-06-14

== Meta

The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content may not always be associated with version changes to the resource..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Meta[Meta, window="_blank"]


=== Diagram

[plantuml, Meta, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class Meta {
	lastUpdated : Instant 0..1
	profile : String 0..*
	security : Coding 0..*
	tag : Coding 0..*
	versionId : String 0..1
}

--

=== Properties
lastUpdated:: When the resource last changed - e.g. when the version changed.
profile:: A list of profiles (references to [StructureDefinition](structuredefinition.html#) resources) that this resource claims to conform to. The URL is a reference to [StructureDefinition.url]().
security:: Security labels applied to this resource. These tags connect specific resources to the overall security policy and infrastructure.
tag:: Tags applied to this resource. Tags are intended to be used to identify and relate resources to process and workflow, and applications are not required to consider the tags when interpreting the meaning of a resource.
versionId:: The version specific identifier, as it appears in the version portion of the URL. This values changes when the resource is created, updated, or deleted.


