// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= Patient

Generated from FHIR 3.0.1.11917 on 2019-06-14

== Patient

Demographics and other administrative information about an individual or animal receiving care or other health-related services..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Patient[Patient, window="_blank"]


=== Diagram

[plantuml, Patient, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class Patient {
	active : Boolean 0..1
	address : Address 0..*
	animal : PatientAnimal 0..1
	birthDate : Date 0..1
	communication : PatientCommunication 0..*
	contact : PatientContact 0..*
	deceasedBoolean : Boolean 0..1
	deceasedDateTime : DateTime 0..1
	gender : AdministrativeGender 0..1
	generalPractitioner : Reference 0..*
	identifier : Identifier 0..*
	link : PatientLink 0..*
	managingOrganization : Reference 0..1
	maritalStatus : CodeableConcept 0..1
	multipleBirthBoolean : Boolean 0..1
	multipleBirthInteger : Integer 0..1
	name : HumanName 0..*
	photo : Attachment 0..*
	telecom : ContactPoint 0..*
}

--

=== Properties
active:: Whether this patient record is in active use.
address:: None
animal:: This patient is known to be an animal.
birthDate:: None
communication:: Languages which may be used to communicate with the patient about his or her health.
contact:: None
deceasedBoolean:: None
deceasedDateTime:: None
gender:: Administrative Gender - the gender that the patient is considered to have for administration and record keeping purposes.
generalPractitioner:: Patient's nominated care provider.
identifier:: None
link:: Link to another patient resource that concerns the same actual patient.
managingOrganization:: None
maritalStatus:: This field contains a patient's most recent marital (civil) status.
multipleBirthBoolean:: Indicates whether the patient is part of a multiple (bool) or indicates the actual birth order (integer).
multipleBirthInteger:: Indicates whether the patient is part of a multiple (bool) or indicates the actual birth order (integer).
name:: A name associated with the individual.
photo:: None
telecom:: A contact detail (e.g. a telephone number or an email address) by which the individual may be contacted.




== PatientAnimal

This patient is known to be an animal..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Patient[Patient, window="_blank"]


=== Diagram

[plantuml, PatientAnimal, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class PatientAnimal {
	breed : CodeableConcept 0..1
	genderStatus : CodeableConcept 0..1
	species : CodeableConcept 1..1
}

--

=== Properties
breed:: Identifies the detailed categorization of the kind of animal.
genderStatus:: Indicates the current state of the animal's reproductive organs.
species:: Identifies the high level taxonomic categorization of the kind of animal.




== PatientCommunication

Languages which may be used to communicate with the patient about his or her health..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Patient[Patient, window="_blank"]


=== Diagram

[plantuml, PatientCommunication, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class PatientCommunication {
	language : CodeableConcept 1..1
	preferred : Boolean 0..1
}

--

=== Properties
language:: The ISO-639-1 alpha 2 code in lower case for the language, optionally followed by a hyphen and the ISO-3166-1 alpha 2 code for the region in upper case; e.g. "en" for English, or "en-US" for American English versus "en-EN" for England English.
preferred:: Indicates whether or not the patient prefers this language (over other languages he masters up a certain level).




== PatientContact

A contact party (e.g. guardian, partner, friend) for the patient.

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Patient[Patient, window="_blank"]


=== Diagram

[plantuml, PatientContact, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class PatientContact {
	address : Address 0..1
	gender : AdministrativeGender 0..1
	name : HumanName 0..1
	organization : Reference 0..1
	period : Period 0..1
	relationship : CodeableConcept 0..*
	telecom : ContactPoint 0..*
}

--

=== Properties
address:: None
gender:: Administrative Gender - the gender that the contact person is considered to have for administration and record keeping purposes.
name:: None
organization:: Organization on behalf of which the contact is acting or for which the contact is working.
period:: None
relationship:: The nature of the relationship between the patient and the contact person.
telecom:: A contact detail for the person, e.g. a telephone number or an email address.




== PatientLink

Link to another patient resource that concerns the same actual patient..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Patient[Patient, window="_blank"]


=== Diagram

[plantuml, PatientLink, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class PatientLink {
	other : Reference 1..1
	type : LinkType 1..1
}

--

=== Properties
other:: The other patient resource that the link refers to.
type:: The type of link between this patient resource and another patient resource.


