// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= Procedure

Generated from FHIR 3.0.1.11917 on 2019-06-14

== Procedure

An action that is or was performed on a patient. This can be a physical intervention like an operation, or less invasive like counseling or hypnotherapy..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Procedure[Procedure, window="_blank"]


=== Diagram

[plantuml, Procedure, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class Procedure {
	basedOn : Reference 0..*
	bodySite : CodeableConcept 0..*
	category : CodeableConcept 0..1
	code : CodeableConcept 0..1
	complication : CodeableConcept 0..*
	complicationDetail : Reference 0..*
	context : Reference 0..1
	definition : Reference 0..*
	focalDevice : ProcedureFocalDevice 0..*
	followUp : CodeableConcept 0..*
	identifier : Identifier 0..*
	location : Reference 0..1
	notDone : Boolean 0..1
	notDoneReason : CodeableConcept 0..1
	note : Annotation 0..*
	outcome : CodeableConcept 0..1
	partOf : Reference 0..*
	performedDateTime : DateTime 0..1
	performedPeriod : Period 0..1
	performer : ProcedurePerformer 0..*
	reasonCode : CodeableConcept 0..*
	reasonReference : Reference 0..*
	report : Reference 0..*
	status : EventStatus 1..1
	subject : Reference 1..1
	usedCode : CodeableConcept 0..*
	usedReference : Reference 0..*
}

--

=== Properties
basedOn:: A reference to a resource that contains details of the request for this procedure.
bodySite:: Detailed and structured anatomical location information. Multiple locations are allowed - e.g. multiple punch biopsies of a lesion.
category:: A code that classifies the procedure for searching, sorting and display purposes (e.g. "Surgical Procedure").
code:: The specific procedure that is performed. Use text if the exact nature of the procedure cannot be coded (e.g. "Laparoscopic Appendectomy").
complication:: Any complications that occurred during the procedure, or in the immediate post-performance period. These are generally tracked separately from the notes, which will typically describe the procedure itself rather than any 'post procedure' issues.
complicationDetail:: Any complications that occurred during the procedure, or in the immediate post-performance period.
context:: The encounter during which the procedure was performed.
definition:: A protocol, guideline, orderset or other definition that was adhered to in whole or in part by this procedure.
focalDevice:: A device that is implanted, removed or otherwise manipulated (calibration, battery replacement, fitting a prosthesis, attaching a wound-vac, etc.) as a focal portion of the Procedure.
followUp:: If the procedure required specific follow up - e.g. removal of sutures. The followup may be represented as a simple note, or could potentially be more complex in which case the CarePlan resource can be used.
identifier:: This records identifiers associated with this procedure that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate (e.g. in CDA documents, or in written / printed documentation).
location:: The location where the procedure actually happened.  E.g. a newborn at home, a tracheostomy at a restaurant.
notDone:: Set this to true if the record is saying that the procedure was NOT performed.
notDoneReason:: A code indicating why the procedure was not performed.
note:: Any other notes about the procedure.  E.g. the operative notes.
outcome:: The outcome of the procedure - did it resolve reasons for the procedure being performed?
partOf:: A larger event of which this particular procedure is a component or step.
performedDateTime:: The date(time)/period over which the procedure was performed. Allows a period to support complex procedures that span more than one date, and also allows for the length of the procedure to be captured.
performedPeriod:: The date(time)/period over which the procedure was performed. Allows a period to support complex procedures that span more than one date, and also allows for the length of the procedure to be captured.
performer:: Limited to 'real' people rather than equipment.
reasonCode:: The coded reason why the procedure was performed. This may be coded entity of some type, or may simply be present as text.
reasonReference:: The condition that is the reason why the procedure was performed.
report:: This could be a histology result, pathology report, surgical report, etc..
status:: A code specifying the state of the procedure. Generally this will be in-progress or completed state.
subject:: The person, animal or group on which the procedure was performed.
usedCode:: Identifies coded items that were used as part of the procedure.
usedReference:: Identifies medications, devices and any other substance used as part of the procedure.




== ProcedureFocalDevice

A device that is implanted, removed or otherwise manipulated (calibration, battery replacement, fitting a prosthesis, attaching a wound-vac, etc.) as a focal portion of the Procedure..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Procedure[Procedure, window="_blank"]


=== Diagram

[plantuml, ProcedureFocalDevice, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class ProcedureFocalDevice {
	action : CodeableConcept 0..1
	manipulated : Reference 1..1
}

--

=== Properties
action:: The kind of change that happened to the device during the procedure.
manipulated:: The device that was manipulated (changed) during the procedure.




== ProcedurePerformer

Limited to 'real' people rather than equipment..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Procedure[Procedure, window="_blank"]


=== Diagram

[plantuml, ProcedurePerformer, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class ProcedurePerformer {
	actor : Reference 1..1
	onBehalfOf : Reference 0..1
	role : CodeableConcept 0..1
}

--

=== Properties
actor:: The practitioner who was involved in the procedure.
onBehalfOf:: The organization the device or practitioner was acting on behalf of.
role:: For example: surgeon, anaethetist, endoscopist.


