// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= Quantity

Generated from FHIR 3.0.1.11917 on 2019-06-14

== Quantity

A measured amount (or an amount that can potentially be measured). Note that measured amounts include amounts that are not precisely quantified, including amounts involving arbitrary units and floating currencies..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Quantity[Quantity, window="_blank"]


=== Diagram

[plantuml, Quantity, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class Quantity {
	code : String 0..1
	comparator : QuantityComparator 0..1
	system : String 0..1
	unit : String 0..1
	value : Decimal 0..1
}

--

=== Properties
code:: A computer processable form of the unit in some unit representation system.
comparator:: How the value should be understood and represented - whether the actual value is greater or less than the stated value due to measurement issues; e.g. if the comparator is "<" , then the real value is < stated value.
system:: The identification of the system that provides the coded form of the unit.
unit:: A human-readable form of the unit.
value:: The value of the measured amount. The value includes an implicit precision in the presentation of the value.


