// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= ReferralRequest

Generated from FHIR 3.0.1.11917 on 2019-06-14

== ReferralRequest

Used to record and send details about a request for referral service or transfer of a patient to the care of another provider or provider organization..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/ReferralRequest[ReferralRequest, window="_blank"]


=== Diagram

[plantuml, ReferralRequest, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class ReferralRequest {
	authoredOn : DateTime 0..1
	basedOn : Reference 0..*
	context : Reference 0..1
	definition : Reference 0..*
	description : String 0..1
	groupIdentifier : Identifier 0..1
	identifier : Identifier 0..*
	intent : RequestIntent 1..1
	note : Annotation 0..*
	occurrenceDateTime : DateTime 0..1
	occurrencePeriod : Period 0..1
	priority : RequestPriority 0..1
	reasonCode : CodeableConcept 0..*
	reasonReference : Reference 0..*
	recipient : Reference 0..*
	relevantHistory : Reference 0..*
	replaces : Reference 0..*
	requester : ReferralRequestRequester 0..1
	serviceRequested : CodeableConcept 0..*
	specialty : CodeableConcept 0..1
	status : RequestStatus 1..1
	subject : Reference 1..1
	supportingInfo : Reference 0..*
	type : CodeableConcept 0..1
}

--

=== Properties
authoredOn:: Date/DateTime of creation for draft requests and date of activation for active requests.
basedOn:: Indicates any plans, proposals or orders that this request is intended to satisfy - in whole or in part.
context:: The encounter at which the request for referral or transfer of care is initiated.
definition:: A protocol, guideline, orderset or other definition that is adhered to in whole or in part by this request.
description:: The reason element gives a short description of why the referral is being made, the description expands on this to support a more complete clinical summary.
groupIdentifier:: The business identifier of the logical "grouping" request/order that this referral is a part of.
identifier:: Business identifier that uniquely identifies the referral/care transfer request instance.
intent:: Distinguishes the "level" of authorization/demand implicit in this request.
note:: Comments made about the referral request by any of the participants.
occurrenceDateTime:: The period of time within which the services identified in the referral/transfer of care is specified or required to occur.
occurrencePeriod:: The period of time within which the services identified in the referral/transfer of care is specified or required to occur.
priority:: An indication of the urgency of referral (or where applicable the type of transfer of care) request.
reasonCode:: Description of clinical condition indicating why referral/transfer of care is requested.  For example:  Pathological Anomalies, Disabled (physical or mental),  Behavioral Management.
reasonReference:: Indicates another resource whose existence justifies this request.
recipient:: The healthcare provider(s) or provider organization(s) who/which is to receive the referral/transfer of care request.
relevantHistory:: Links to Provenance records for past versions of this resource or fulfilling request or event resources that identify key state transitions or updates that are likely to be relevant to a user looking at the current version of the resource.
replaces:: Completed or terminated request(s) whose function is taken by this new request.
requester:: The individual who initiated the request and has responsibility for its activation.
serviceRequested:: The service(s) that is/are requested to be provided to the patient.  For example: cardiac pacemaker insertion.
specialty:: Indication of the clinical domain or discipline to which the referral or transfer of care request is sent.  For example: Cardiology Gastroenterology Diabetology.
status:: The status of the authorization/intention reflected by the referral request record.
subject:: The patient who is the subject of a referral or transfer of care request.
supportingInfo:: Any additional (administrative, financial or clinical) information required to support request for referral or transfer of care.  For example: Presenting problems/chief complaints Medical History Family History Alerts Allergy/Intolerance and Adverse Reactions Medications Observations/Assessments (may include cognitive and fundtional assessments) Diagnostic Reports Care Plan.
type:: An indication of the type of referral (or where applicable the type of transfer of care) request.




== ReferralRequestRequester

The individual who initiated the request and has responsibility for its activation..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/ReferralRequest[ReferralRequest, window="_blank"]


=== Diagram

[plantuml, ReferralRequestRequester, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class ReferralRequestRequester {
	agent : Reference 1..1
	onBehalfOf : Reference 0..1
}

--

=== Properties
agent:: The device, practitioner, etc. who initiated the request.
onBehalfOf:: The organization the device or practitioner was acting on behalf of.


