// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= Reference

Generated from FHIR 3.0.1.11917 on 2019-06-14

== Reference

A reference from one resource to another.

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Reference[Reference, window="_blank"]


=== Diagram

[plantuml, Reference, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class Reference {
	display : String 0..1
	identifier : Identifier 0..1
	reference : String 0..1
}

--

=== Properties
display:: Plain text narrative that identifies the resource in addition to the resource reference.
identifier:: An identifier for the other resource. This is used when there is no way to reference the other resource directly, either because the entity is not available through a FHIR server, or because there is no way for the author of the resource to convert a known identifier to an actual location. There is no requirement that a Reference.identifier point to something that is actually exposed as a FHIR instance, but it SHALL point to a business concept that would be expected to be exposed as a FHIR instance, and that instance would need to be of a FHIR resource type allowed by the reference.
reference:: A reference to a location at which the other resource is found. The reference may be a relative reference, in which case it is relative to the service base URL, or an absolute URL that resolves to the location where the resource is found. The reference may be version specific or not. If the reference is not to a FHIR RESTful server, then it should be assumed to be version specific. Internal fragment references (start with '#') refer to contained resources.


