// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= SampledData

Generated from FHIR 3.0.1.11917 on 2019-06-14

== SampledData

A series of measurements taken by a device, with upper and lower limits. There may be more than one dimension in the data..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/SampledData[SampledData, window="_blank"]


=== Diagram

[plantuml, SampledData, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class SampledData {
	data : String 1..1
	dimensions : Integer 1..1
	factor : Decimal 0..1
	lowerLimit : Decimal 0..1
	origin : Quantity 1..1
	period : Decimal 1..1
	upperLimit : Decimal 0..1
}

--

=== Properties
data:: A series of data points which are decimal values separated by a single space (character u20). The special values "E" (error), "L" (below detection limit) and "U" (above detection limit) can also be used in place of a decimal value.
dimensions:: The number of sample points at each time point. If this value is greater than one, then the dimensions will be interlaced - all the sample points for a point in time will be recorded at once.
factor:: A correction factor that is applied to the sampled data points before they are added to the origin.
lowerLimit:: The lower limit of detection of the measured points. This is needed if any of the data points have the value "L" (lower than detection limit).
origin:: The base quantity that a measured value of zero represents. In addition, this provides the units of the entire measurement series.
period:: The length of time between sampling times, measured in milliseconds.
upperLimit:: The upper limit of detection of the measured points. This is needed if any of the data points have the value "U" (higher than detection limit).


