// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= Specimen

Generated from FHIR 3.0.1.11917 on 2019-06-14

== Specimen

A sample to be used for analysis..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Specimen[Specimen, window="_blank"]


=== Diagram

[plantuml, Specimen, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class Specimen {
	accessionIdentifier : Identifier 0..1
	collection : SpecimenCollection 0..1
	container : SpecimenContainer 0..*
	identifier : Identifier 0..*
	note : Annotation 0..*
	parent : Reference 0..*
	processing : SpecimenProcessing 0..*
	receivedTime : DateTime 0..1
	request : Reference 0..*
	status : SpecimenStatus 0..1
	subject : Reference 1..1
	type : CodeableConcept 0..1
}

--

=== Properties
accessionIdentifier:: The identifier assigned by the lab when accessioning specimen(s). This is not necessarily the same as the specimen identifier, depending on local lab procedures.
collection:: Details concerning the specimen collection.
container:: The container holding the specimen.  The recursive nature of containers; i.e. blood in tube in tray in rack is not addressed here.
identifier:: Id for specimen.
note:: To communicate any details or issues about the specimen or during the specimen collection. (for example: broken vial, sent with patient, frozen).
parent:: Reference to the parent (source) specimen which is used when the specimen was either derived from or a component of another specimen.
processing:: Details concerning processing and processing steps for the specimen.
receivedTime:: Time when specimen was received for processing or testing.
request:: Details concerning a test or procedure request that required a specimen to be collected.
status:: The availability of the specimen.
subject:: None
type:: The kind of material that forms the specimen.




== SpecimenCollection

Details concerning the specimen collection..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Specimen[Specimen, window="_blank"]


=== Diagram

[plantuml, SpecimenCollection, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class SpecimenCollection {
	bodySite : CodeableConcept 0..1
	collectedDateTime : DateTime 0..1
	collectedPeriod : Period 0..1
	collector : Reference 0..1
	method : CodeableConcept 0..1
	quantity : Quantity 0..1
}

--

=== Properties
bodySite:: Anatomical location from which the specimen was collected (if subject is a patient). This is the target site.  This element is not used for environmental specimens.
collectedDateTime:: Time when specimen was collected from subject - the physiologically relevant time.
collectedPeriod:: Time when specimen was collected from subject - the physiologically relevant time.
collector:: Person who collected the specimen.
method:: A coded value specifying the technique that is used to perform the procedure.
quantity:: The quantity of specimen collected; for instance the volume of a blood sample, or the physical measurement of an anatomic pathology sample.




== SpecimenContainer

The container holding the specimen.  The recursive nature of containers; i.e. blood in tube in tray in rack is not addressed here..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Specimen[Specimen, window="_blank"]


=== Diagram

[plantuml, SpecimenContainer, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class SpecimenContainer {
	additiveCodeableConcept : CodeableConcept 0..1
	additiveReference : Reference 0..1
	capacity : Quantity 0..1
	description : String 0..1
	identifier : Identifier 0..*
	specimenQuantity : Quantity 0..1
	type : CodeableConcept 0..1
}

--

=== Properties
additiveCodeableConcept:: Introduced substance to preserve, maintain or enhance the specimen. Examples: Formalin, Citrate, EDTA.
additiveReference:: Introduced substance to preserve, maintain or enhance the specimen. Examples: Formalin, Citrate, EDTA.
capacity:: The capacity (volume or other measure) the container may contain.
description:: None
identifier:: Id for container. There may be multiple; a manufacturer's bar code, lab assigned identifier, etc. The container ID may differ from the specimen id in some circumstances.
specimenQuantity:: The quantity of specimen in the container; may be volume, dimensions, or other appropriate measurements, depending on the specimen type.
type:: The type of container associated with the specimen (e.g. slide, aliquot, etc.).




== SpecimenProcessing

Details concerning processing and processing steps for the specimen..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Specimen[Specimen, window="_blank"]


=== Diagram

[plantuml, SpecimenProcessing, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class SpecimenProcessing {
	additive : Reference 0..*
	description : String 0..1
	procedure : CodeableConcept 0..1
	timeDateTime : DateTime 0..1
	timePeriod : Period 0..1
}

--

=== Properties
additive:: None
description:: None
procedure:: A coded value specifying the procedure used to process the specimen.
timeDateTime:: A record of the time or period when the specimen processing occurred.  For example the time of sample fixation or the period of time the sample was in formalin.
timePeriod:: A record of the time or period when the specimen processing occurred.  For example the time of sample fixation or the period of time the sample was in formalin.


