// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= Substance

Generated from FHIR 3.0.1.11917 on 2019-06-14

== Substance

A homogeneous material with a definite composition.

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Substance[Substance, window="_blank"]


=== Diagram

[plantuml, Substance, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class Substance {
	category : CodeableConcept 0..*
	code : CodeableConcept 1..1
	description : String 0..1
	identifier : Identifier 0..*
	ingredient : SubstanceIngredient 0..*
	instance : SubstanceInstance 0..*
	status : FHIRSubstanceStatus 0..1
}

--

=== Properties
category:: A code that classifies the general type of substance.  This is used  for searching, sorting and display purposes.
code:: A code (or set of codes) that identify this substance.
description:: A description of the substance - its appearance, handling requirements, and other usage notes.
identifier:: Unique identifier for the substance.
ingredient:: A substance can be composed of other substances.
instance:: Substance may be used to describe a kind of substance, or a specific package/container of the substance: an instance.
status:: A code to indicate if the substance is actively used.




== SubstanceIngredient

A substance can be composed of other substances..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Substance[Substance, window="_blank"]


=== Diagram

[plantuml, SubstanceIngredient, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class SubstanceIngredient {
	quantity : Ratio 0..1
	substanceCodeableConcept : CodeableConcept 1..1
	substanceReference : Reference 1..1
}

--

=== Properties
quantity:: The amount of the ingredient in the substance - a concentration ratio.
substanceCodeableConcept:: Another substance that is a component of this substance.
substanceReference:: Another substance that is a component of this substance.




== SubstanceInstance

Substance may be used to describe a kind of substance, or a specific package/container of the substance: an instance..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Substance[Substance, window="_blank"]


=== Diagram

[plantuml, SubstanceInstance, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class SubstanceInstance {
	expiry : DateTime 0..1
	identifier : Identifier 0..1
	quantity : Quantity 0..1
}

--

=== Properties
expiry:: When the substance is no longer valid to use. For some substances, a single arbitrary date is used for expiry.
identifier:: Identifier associated with the package/container (usually a label affixed directly).
quantity:: The amount of the substance.


