// Settings:
:doctype: book
:toc: left
:toclevels: 4
:icons: font
:source-highlighter: prettify
:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

= Timing

Generated from FHIR 3.0.1.11917 on 2019-06-14

== Timing

Specifies an event that may occur multiple times. Timing schedules are used to record when things are planned, expected or requested to occur. The most common usage is in dosage instructions for medications. They are also used when planning care of various kinds, and may be used for reporting the schedule to which past regular activities were carried out..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Timing[Timing, window="_blank"]


=== Diagram

[plantuml, Timing, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class Timing {
	code : CodeableConcept 0..1
	event : DateTime 0..*
	repeat : TimingRepeat 0..1
}

--

=== Properties
code:: A code for the timing schedule. Some codes such as BID are ubiquitous, but many institutions define their own additional codes. If a code is provided, the code is understood to be a complete statement of whatever is specified in the structured timing data, and either the code or the data may be used to interpret the Timing, with the exception that .repeat.bounds still applies over the code (and is not contained in the code).
event:: Identifies specific times when the event occurs.
repeat:: A set of rules that describe when the event is scheduled.




== TimingRepeat

A set of rules that describe when the event is scheduled..

FHIR Reference: http://hl7.org/fhir/StructureDefinition/Timing[Timing, window="_blank"]


=== Diagram

[plantuml, TimingRepeat, svg]
--
skinparam Shadowing false
skinparam padding 2
skinparam class {
    BorderColor Black
}

hide methods

class TimingRepeat {
	boundsDuration : Duration 0..1
	boundsPeriod : Period 0..1
	boundsRange : Range 0..1
	count : Integer 0..1
	countMax : Integer 0..1
	dayOfWeek : DaysOfWeek 0..*
	duration : Decimal 0..1
	durationMax : Decimal 0..1
	durationUnit : String 0..1
	frequency : Integer 0..1
	frequencyMax : Integer 0..1
	offset : Integer 0..1
	period : Decimal 0..1
	periodMax : Decimal 0..1
	periodUnit : String 0..1
	timeOfDay : Time 0..*
	when : String 0..*
}

--

=== Properties
boundsDuration:: Either a duration for the length of the timing schedule, a range of possible length, or outer bounds for start and/or end limits of the timing schedule.
boundsPeriod:: Either a duration for the length of the timing schedule, a range of possible length, or outer bounds for start and/or end limits of the timing schedule.
boundsRange:: Either a duration for the length of the timing schedule, a range of possible length, or outer bounds for start and/or end limits of the timing schedule.
count:: A total count of the desired number of repetitions.
countMax:: A maximum value for the count of the desired repetitions (e.g. do something 6-8 times).
dayOfWeek:: If one or more days of week is provided, then the action happens only on the specified day(s).
duration:: How long this thing happens for when it happens.
durationMax:: The upper limit of how long this thing happens for when it happens.
durationUnit:: The units of time for the duration, in UCUM units.
frequency:: The number of times to repeat the action within the specified period / period range (i.e. both period and periodMax provided).
frequencyMax:: If present, indicates that the frequency is a range - so to repeat between [frequency] and [frequencyMax] times within the period or period range.
offset:: The number of minutes from the event. If the event code does not indicate whether the minutes is before or after the event, then the offset is assumed to be after the event.
period:: Indicates the duration of time over which repetitions are to occur; e.g. to express "3 times per day", 3 would be the frequency and "1 day" would be the period.
periodMax:: If present, indicates that the period is a range from [period] to [periodMax], allowing expressing concepts such as "do this once every 3-5 days.
periodUnit:: The units of time for the period in UCUM units.
timeOfDay:: Specified time of day for action to take place.
when:: Real world events that the occurrence of the event should be tied to.


