# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
end

desc "Generate FHIR models documentation"
lane :generate_fhir_model_doc do | options |
  fhir_doc
end

desc "Generate FHIR Java models"
lane :generate_fhir_java_models do | options |
  fhir_java_stu3
  fhir_java_r4
end


