name: D4L Publish Artifact

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PACKAGE_REGISTRY_USERNAME: ${{ secrets.PACKAGE_REGISTRY_USERNAME }}
      PACKAGE_REGISTRY_TOKEN: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodule: 'recursive'
      - name: Cleanup
        run: ./gradlew clean
      - name: Generate models
        run: bundle exec fastlane generate_fhir_java_models
      - name: Build project
        run: ./gradlew build
      - name: Publish artifacts
        run: ./gradlew publish
